author: GitHub User
name: Angelina Moreno Robledo

title: Angelina Moreno Robledo
description: >
  Fue mi curiosidad por lo desconocido y un grupo de mujeres que buscaban insertar a más mujeres
  en el mundo de la programación lo que hoy hace que este escribiendo estas lineas a través de un
  tema de Jekyll que he creado con mucho cariño y con el que pretendo hacer un pequeño recopilatorio
  sobre algunos de los experimentos que voy llevando a cabo.


#   If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# http://127.0.0.1:4000
# this means to ignore newlines until "baseurl:"


email: your-email@domain.com

# social links:

twitter_username: anxhe_
github_username:  anxhe
linkedin_username: angelinamoreno

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# baseurl: http://127.0.0.1:4000
header_pages:
  - index.md
  - blog.md

# Config section the home


# Build settings
markdown: kramdown

theme_jekyll-theme-experiment:
  portfolio:
    title: Portafolio
    projects:

      - name: Jekyll Theme experiment
        github: https://github.com/anxhe/jekyll-theme-experiment
        link: https://anxhe.github.io/jekyll-theme-experiment/
        img_relative_url: /assets/jekyll-theme-experiment.png

      - name: Editor Living Style Guide
        github: https://github.com/fanxhe/livingstyleguide-editor
        link: http://try.livingstyleguide.org/
        img_relative_url: /assets/linvingstyleguide-editor.png

      - name: Slack-bot
        github: https://github.com/anxhe/gordify
        link: https://gordify.herokuapp.com/
        img_relative_url: /assets/slack-bot.png

  tools:
    - relative_url: /assets/icons/html5.svg
    - relative_url: /assets/icons/git/git-original.svg
    - relative_url: /assets/icons/github/github-original.svg
    - relative_url: /assets/icons/bitbucket/bitbucket-original.svg
    - relative_url: /assets/icons/express/express-original.svg
    - relative_url: /assets/icons/angularjs/angularjs-original.svg
    - relative_url: /assets/icons/javascript/javascript-original.svg
    - relative_url: /assets/icons/mongo/mongo.svg
    - relative_url: /assets/icons/sass/sass.svg
    - relative_url: /assets/icons/jasmine/jasmine.svg
    - relative_url: /assets/icons/mocha/mocha.svg
    - relative_url: /assets/icons/ruby/ruby-original.svg
    - relative_url: /assets/icons/heroku/heroku-original.svg

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
